[".cache/github/git-credential-manager.json"]
  type = "file"
  refreshPeriod = "168h" # 1-week
  url = "https://api.github.com/repos/git-ecosystem/git-credential-manager/releases/latest"
[".cache/github-releases/age-yubikey-plugin.json"]
  type = "file"
  refreshPeriod = "168h"
  url = "https://api.github.com/repos/str4d/age-plugin-yubikey/releases/latest"
[".cache/github-releases/github-monospace.json"]
  type = "file"
  refreshPeriod = "4374h" # 6 months
  url = "https://api.github.com/repos/githubnext/monaspace/releases/latest"